services:
  go-app.development:
    build:
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/go-app.development
    command:
      - zsh
      - --login
      - -c
      - |
        go-inotifywait.zsh
    environment:
      - ENV_UNIQUE_ID
    init: true
    user: "${UID:-0}:${GID:-0}"
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace/http-ok-whatever
  go-app.production:
    build:
      additional_contexts:
        - workspace=workspace
      args:
        GIT_SHORT_SHA:
        GID: ${GID:-0}
        UID: ${UID:-0}
      context: Dockerfile.d/go-app.production
    init: true
    profiles:
      - only-production
