name: test-the-app

on:
  push:
    paths:
      - ".github/workflows/**"
      - "compose.yaml"
      - "Dockerfile.d/go-app.production/**"
      - "workspace/**"
  workflow_dispatch:

jobs:
  test-containers:
    name: test-containers
    secrets: inherit
    uses: ./.github/workflows/_test-the-app-using-container.yaml
    with:
      compose-service-name: go-app.development
